### ISSUE TITLE
Disclosure Properties page redesign

### ISSUE THREAD

**Issue by Ben-Richards** [fundapps/fundapps.github.io#13]
## Problem

- docs.fundapps.co/disclosureProperties.html is too detailed.
- Prospects are seeing the full spec and getting overwhelmed with all the data points we are asking for not realising that depending on their holdings, not all of them are required.
- We are making the sales cycle more difficult by not displaying the data in a more user friendly manner
- We are potentially losing sales over prospects misunderstanding the scope of our data spec
- Even once signed, there are too many questions and confusion over what properties are needed for what assetclass.

## Requirement

- To allow a prospect to isolate exactly which data points they are required to send to Rapptr depending on a kind of instruments they hold
- To allow a prospect to toggle to asset classes they hold ( + sovereign debt)
- Possibly allow a prospect to toggle between the jurisdictions they hold (I would prefer not to allow this as
   - There are a lot of counties
   - It is dangerous as just because they they think they don’t trade in one country doesn’t mean they don’t have a disclosure obligation there
- To allow a prospect to download the filtered spec in a nice manner, so they can take this to the relevant teams, rather than having to print all 18 pages which it is right now.

## Style
- Dropdown where a user can select the various attributes that are applicable to their security master

![image](https://user-images.githubusercontent.com/13979386/29403180-6fc75bd6-832f-11e7-9382-5fb5ce5ccf3e.png)

**Comment by ApwFA** [comment]
Done
