### ISSUE TITLE
Add Bloomberg mappings field and disclaimer on shareholding disclosure

### ISSUE THREAD

**Issue by csneds** [fundapps/fundapps.github.io#9]
Disclaimer "Although every effort has been made to provide complete and accurate information, FundApps makes no guarantees, express or implied, or representations as to the accuracy of this content. FundApps assumes no liability or responsibility for any error or omissions in these mappings" 

So we can send to clients without having to copy into excel - We HATE excel

**Comment by ApwFA** [comment]
Fixed :)
